from __future__ import annotations

from typing import Any, Protocol


class EntityRepository(Protocol):
    @property
    def entities(self) -> dict[str, list[dict[str, Any]]]: ...

    def list(self, entity_name: str) -> list[dict[str, Any]]: ...

    def get(self, entity_name: str, index: int) -> dict[str, Any]: ...

    def add(self, entity_name: str, data: Any) -> dict[str, Any]: ...

    def update(self, entity_name: str, index: int, data: Any) -> dict[str, Any]: ...

    def delete(self, entity_name: str, index: int) -> dict[str, Any]: ...

    def clear(self) -> None: ...
